import '../styles/globals.css'
import { ManifestoContext } from '../lib/context'

function MyApp({ Component, pageProps }) {
  return (
    <ManifestoContext.Provider value={
      [
        {
          id: 3,
          from: 1,
          author: '0x968...5dD',
          contract: '0x9fbebbd9d725c137cc15926eefa541018fa2498a581d15c2373c442839eeb05b',
          content: 'EMERGENT ART a working definition From the whole For the whole "Our separation from each other is an optical illusion of consciousness." -Albert Einstein There is a new art form taking shape, old as time. Art of the cosmos. From the spark at the beginning go time. Our mythologies, cities, civilization, bunion fungi, ripples in a quartz of metal, radioactive decay, Ethereum ecosystem, the nuclei in, Why is there something rather than nothing? Not a new artform. Although emergent phenomena are everywhere in art, there has yet to be a techno-ecosystem to scale an emergent art form. Our emergent potential has been controlled by overlords, The mythmaking a teenager does in their bedroom to the latest Drake song is debased, instrumentalized, raped of its potential. But now we have the foundation, the technoecosystem, for a true emergent art. The centralized means of distribution of the page, the classical score, the LLC, are giving way to decentralized ecosystems. Emergent art is blossoming forth. Loot (for adventurers) is proof of concept. The feature that makes this artform distinct, is that the work does not exist without the audience. Although Drake the Web 2-era audience participated in the meaning of our secular mythologies; Drake, Taylor, Kanye, etc. this theatre of celebrities has been talking to the audience. The Drake song still exists if there is no one to listen to it. The emergent property in its fan culture, add extra layers of meaning. If there is no one to mint loot, loot is just a list of items on the Blockchain.The audience is the author. An[a]artwork that encompasses every medium An artwork that honours the artist emergent in everyone and everything An artwork free from the top-down tyranny of celebrity A democratic artwork Indivisible, emergent. I, you, we Tear down our lone-genius idolatry, seed -mythologies- from the whole, for the whole. Love, EMERGENCE IS DANGEROUS In this medium, decisions HAVE to be made on behalf of the WHOLE. Emergent art is, by definition, a chaotic process that is not in control of any one person. It also is, by definition, impossible to predict second and third-order consequences. Its to non-linear dynamics, black swans, Should we abandon the discipline altogether? Are we all at risk of becoming Viktor Frankensteins? The work of the seed is to design the boundary conditions, from which life grows. CATASTROPHIC RISK As we face a buffet of catastrophic risks; we need every action to be guided by the question: how can I maximize my contribution to the whole? My love for the whole? Any system with rivalry and exponential tech will self-destruct. Its in the forming of the grammar, that will be built by community rath'
        },
        {
          id: 2,
          from: 0,
          author: '0x968...5dD',
          contract: '0x9fbebbd9d725c137cc15926eefa541018fa2498a581d15c2373c442839eeb05b',
          content: 'EMERGENT ART a working definition From the whole For the whole "Our separation from each other is an optical illusion of consciousness." -Albert Einstein There is a new art form taking shape, old as time. Art of the cosmos. From the spark at the beginning go time. Our mythologies, cities, civilization, bunion fungi, ripples in a quartz of metal, radioactive decay, Ethereum ecosystem, the nuclei in, Why is there something rather than nothing? Not a new artform. Although emergent phenomena are everywhere in art, there has yet to be a techno-ecosystem to scale an emergent art form. Our emergent potential has been controlled by overlords, The mythmaking a teenager does in their bedroom to the latest Drake song is debased, instrumentalized, raped of its potential. But now we have the foundation, the technoecosystem, for a true emergent art. The centralized means of distribution of the page, the classical score, the LLC, are giving way to decentralized ecosystems. Emergent art is blossoming forth. Loot (for adventurers) is proof of concept. The feature that makes this artform distinct, is that the work does not exist without the audience. Although Drake the Web 2-era audience participated in the meaning of our secular mythologies; Drake, Taylor, Kanye, etc. this theatre of celebrities has been talking to the audience. The Drake song still exists if there is no one to listen to it. The emergent property in its fan culture, add extra layers of meaning. If there is no one to mint loot, loot is just a list of items on the Blockchain.The audience is the author. An[a]artwork that encompasses every medium An artwork that honours the artist emergent in everyone and everything An artwork free from the top-down tyranny of celebrity A democratic artwork Indivisible, emergent. I, you, we Tear down our lone-genius idolatry, seed -mythologies- from the whole, for the whole. Love, EMERGENCE IS DANGEROUS In this medium, decisions HAVE to be made on behalf of the WHOLE. Emergent art is, by definition, a chaotic process that is not in control of any one person. It also is, by definition, impossible to predict second and third-order consequences. Its to non-linear dynamics, black swans, Should we abandon the discipline altogether? Are we all at risk of becoming Viktor Frankensteins? The work of the seed is to design the boundary conditions, from which life grows. CATASTROPHIC RISK As we face a buffet of catastrophic risks; we need every action to be guided by the question: how can I maximize my contribution to the whole? My love for the whole? Any system with rivalry and exponential tech will self-destruct. Its in the forming of the grammar, that will be built by community rath'
        },
        {
          id: 1,
          from: 0,
          author: '0x968...5dD',
          contract: '0x9fbebbd9d725c137cc15926eefa541018fa2498a581d15c2373c442839eeb05b',
          content: 'EMERGENT ART a working definition From the whole For the whole "Our separation from each other is an optical illusion of consciousness." -Albert Einstein There is a new art form taking shape, old as time. Art of the cosmos. From the spark at the beginning go time. Our mythologies, cities, civilization, bunion fungi, ripples in a quartz of metal, radioactive decay, Ethereum ecosystem, the nuclei in, Why is there something rather than nothing? Not a new artform. Although emergent phenomena are everywhere in art, there has yet to be a techno-ecosystem to scale an emergent art form. Our emergent potential has been controlled by overlords, The mythmaking a teenager does in their bedroom to the latest Drake song is debased, instrumentalized, raped of its potential. But now we have the foundation, the technoecosystem, for a true emergent art. The centralized means of distribution of the page, the classical score, the LLC, are giving way to decentralized ecosystems. Emergent art is blossoming forth. Loot (for adventurers) is proof of concept. The feature that makes this artform distinct, is that the work does not exist without the audience. Although Drake the Web 2-era audience participated in the meaning of our secular mythologies; Drake, Taylor, Kanye, etc. this theatre of celebrities has been talking to the audience. The Drake song still exists if there is no one to listen to it. The emergent property in its fan culture, add extra layers of meaning. If there is no one to mint loot, loot is just a list of items on the Blockchain.The audience is the author. An[a]artwork that encompasses every medium An artwork that honours the artist emergent in everyone and everything An artwork free from the top-down tyranny of celebrity A democratic artwork Indivisible, emergent. I, you, we Tear down our lone-genius idolatry, seed -mythologies- from the whole, for the whole. Love, EMERGENCE IS DANGEROUS In this medium, decisions HAVE to be made on behalf of the WHOLE. Emergent art is, by definition, a chaotic process that is not in control of any one person. It also is, by definition, impossible to predict second and third-order consequences. Its to non-linear dynamics, black swans, Should we abandon the discipline altogether? Are we all at risk of becoming Viktor Frankensteins? The work of the seed is to design the boundary conditions, from which life grows. CATASTROPHIC RISK As we face a buffet of catastrophic risks; we need every action to be guided by the question: how can I maximize my contribution to the whole? My love for the whole? Any system with rivalry and exponential tech will self-destruct. Its in the forming of the grammar, that will be built by community rath'
        },
        {
          id: 0,
          author: '0x968...5dD',
          contract: '0x9fbebbd9d725c137cc15926eefa541018fa2498a581d15c2373c442839eeb05b',
          content: 'EMERGENT ART a working definition From the whole For the whole "Our separation from each other is an optical illusion of consciousness." -Albert Einstein There is a new art form taking shape, old as time. Art of the cosmos. From the spark at the beginning go time. Our mythologies, cities, civilization, bunion fungi, ripples in a quartz of metal, radioactive decay, Ethereum ecosystem, the nuclei in, Why is there something rather than nothing? Not a new artform. Although emergent phenomena are everywhere in art, there has yet to be a techno-ecosystem to scale an emergent art form. Our emergent potential has been controlled by overlords, The mythmaking a teenager does in their bedroom to the latest Drake song is debased, instrumentalized, raped of its potential. But now we have the foundation, the technoecosystem, for a true emergent art. The centralized means of distribution of the page, the classical score, the LLC, are giving way to decentralized ecosystems. Emergent art is blossoming forth. Loot (for adventurers) is proof of concept. The feature that makes this artform distinct, is that the work does not exist without the audience. Although Drake the Web 2-era audience participated in the meaning of our secular mythologies; Drake, Taylor, Kanye, etc. this theatre of celebrities has been talking to the audience. The Drake song still exists if there is no one to listen to it. The emergent property in its fan culture, add extra layers of meaning. If there is no one to mint loot, loot is just a list of items on the Blockchain.The audience is the author. An[a]artwork that encompasses every medium An artwork that honours the artist emergent in everyone and everything An artwork free from the top-down tyranny of celebrity A democratic artwork Indivisible, emergent. I, you, we Tear down our lone-genius idolatry, seed -mythologies- from the whole, for the whole. Love, EMERGENCE IS DANGEROUS In this medium, decisions HAVE to be made on behalf of the WHOLE. Emergent art is, by definition, a chaotic process that is not in control of any one person. It also is, by definition, impossible to predict second and third-order consequences. Its to non-linear dynamics, black swans, Should we abandon the discipline altogether? Are we all at risk of becoming Viktor Frankensteins? The work of the seed is to design the boundary conditions, from which life grows. CATASTROPHIC RISK As we face a buffet of catastrophic risks; we need every action to be guided by the question: how can I maximize my contribution to the whole? My love for the whole? Any system with rivalry and exponential tech will self-destruct. Its in the forming of the grammar, that will be built by community rath'
        },
      ]
    }>
      <Component {...pageProps} />
    </ManifestoContext.Provider>
  )
}

export default MyApp
