import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState, useContext } from 'react'
import { ManifestoContext } from '../lib/context'


export default function Home() {
  const manifestos = useContext(ManifestoContext);

  return (
    <div>
      <Head>
        <title>The Emergent Art Manifesto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col items-center mt-16 mx-4 mb-24'>
        <section className='flex flex-col items-start'>
          {manifestos.map(manifesto => {
            return (
              <article key={manifesto.id} className='flex items-baseline space-x-2'>
                <Link href={`/manifesto/${manifesto.id}`}><a>{manifesto.id}</a></Link>
                {manifesto.id !== 0 && (
                  <div className='flex items-baseline space-x-2'>
                    <p className='text-sm'>from</p>
                    <Link href={`/manifesto/${manifesto.from}`}><a>{manifesto.from}</a></Link>
                  </div>
                )}
              </article>
            )
          })}
        </section>
      </main>
    </div>
  )
}
